### PR TITLE
[WIP] add up down arrows on fields when the field is selected

### PR DESCRIPTION
**Pull request by RobStino**

### CODE REVIEW

**Comment by RobStino** [comment]
@lukecarbis @kienstra 
This is a quick example of what I think would be the easiest thing for moving around fields.
Screen Capture on 2020-10-26 at 14-40-27
Does having this in place of drag-and-drop for field order, work for you?
Note this PR only has the buttons added on the first field. If you like the look of it, I'll add them to the rest of the fields.

For field resizing, we would defer that to only the button group in the field settings (in the inspector).

Question though, if I have a 50% width field to the left of another 50% width field and I press the "Up" button to move the field up in order, it would actually shift it to the left.
What are your thoughts on this before I dig in to finding a solution?

**Comment by kienstra** [comment]
>Does having this in place of drag-and-drop for field order, work for you?

Yeah, that looks good.

>Question though, if I have a 50% width field to the left of another 50% width field and I press the "Up" button to move the field up in order, it would actually shift it to the left.

Yeah, shifting to the left sounds good in that case.

**Comment by lukecarbis** [comment]
I agree. Up and down works even if it's moving the field left / right.

**Comment by RobStino** [comment]
What about, when it's relevant, the arrow rotates 90 degrees?
Or too fiddly?

**Comment by lukecarbis** [comment]
There would be multiple states depending on where the field is:
- ⬆️ ⬇️
- ⬆️ ➡️
- ⬅️ ⬇️
- ⬅️ ➡️

If it's easy to do that, I'd be open to experimenting with it. But my gut says it's going to be a bit of a pain to implement, so I'd rather just keep it simple.

What do you think @kienstra?

**Comment by kienstra** [comment]
>If it's easy to do that, I'd be open to experimenting with it. But my gut says it's going to be a bit of a pain to implement, so I'd rather just keep it simple.

Yeah, that might be tough to handle all of those states. For starters, maybe just up and down would be good, even if it moves it from left to right.

**Pull request closed without merging**
